### ISSUE TITLE
Issue when trying to integrate

### ISSUE THREAD

**Issue by akshatbhargava123** [ebi-gene-expression-group/atlas-heatmap#21]
I tried to integrate without using `react`, using the renderer provided.

Error Screenshot:
![image](https://user-images.githubusercontent.com/22184427/62823506-122b2880-bbaf-11e9-9833-8865517d5cae.png)

Code link: https://github.com/akshatbhargava123/bluegenes-ebi-expression-atlas-heatmap/blob/master/src/index.js

**Comment by alfonsomunozpomer** [comment]
I think the issue you’re having is because you’re not transpiling the code in Webpack. I suggest you include Babel, since we use fairly modern JavaScript all around.

If you could include the steps you’re following to arrive at a build of your project I could open with a browser, that will definitely help.

**Comment by alfonsomunozpomer** [comment]
I’m closing this issue after being inactive for a year and a half.
